#docker-compose.yml
version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - cache:/cache # Added to support Windows 10 Docker
    environment:
      - SPROCKETS_CACHE=/cache # Added to support Windows 10 Docker
    ports:
    - "3000:3000"
    depends_on:
    - db
volumes:
  cache: # Added to support Windows 10 Docker